name: deploy-dev-manifests

on:
  workflow_run:
    workflows: ["build-api", "build-container-builder", "build-null-operator"]
    types:
      - completed

jobs:
  build-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1
      -
        name: Checkout deployment code
        uses: actions/checkout@v3
        with:
          repository: 'null-channel/nullcloud-deployments'
          token: ${{ secrets.PAT_GITHUB_DEPLOYMENT }}
      - name: Update image tag for api service
        working-directory: ./deployments/null-cloud/base/api/dev/
        run: |
          kustomize edit set image nullchannel/eddington-api-service:${{ github.sha }}
      - name: update image tag for null operator
        working-directory: ./deployments/null-cloud/base/null-operator/dev/
        run: |
          kustomize edit set image nullchannel/eddington-null-operator:${{ github.sha }}
      - name: Update image tag for container builder service
        working-directory: ./deployments/null-cloud/base/container-runner/dev/
        run: |
          kustomize edit set image nullchannel/eddington-container-runner:${{ github.sha }}
      - name: commit to it.
        run: |
          git config --global user.email "null@nulllabs.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha }}"
          git push
